version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Building the project...
      - mvn clean package
      - chmod +x scripts/deploy.sh
      - chown ec2-user:ec2-user target/DevOpsSummative-1.0-SNAPSHOT.jar
      - chown ec2-user:ec2-user scripts/deploy.sh


artifacts:
  files:
    - appspec.yml
    - target/DevOpsSummative-1.0-SNAPSHOT.jar
    - scripts/deploy.sh
