version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Build started on `date`
  test:
    commands:
      - echo Running unit tests...
      - mvn test
  build:
    commands:
      - echo Building the project...
      - mvn clean package
      - chmod +x scripts/deploy.sh

artifacts:
  files:
    - appspec.yml
    - target/DevOpsSummative-1.0-SNAPSHOT.jar
    - scripts/deploy.sh
